name: random_color_app
description: Simple Flutter one page project. Randomly generate and change background color when user tap on screen.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  async: ^2.10.0
  flutter:
    sdk: flutter

  google_fonts: ^4.0.4
  solid_lints: ^0.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
